// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmsfjbvmlsyxrzqvxofx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptc2ZqYnZtbHN5eHJ6cXZ4b2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzI5NTAsImV4cCI6MjA2ODM0ODk1MH0.QkacSXazZckz94CAJSv8iz55S_NHUDSL6YpOifzLLiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});